name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ajusta si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Si est치s usando Node.js

      - name: Build the project
        run: npm run build  # Ajusta esto si est치s usando otro build system

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token para el despliegue
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ajusta si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Si est치s usando Node.js

      - name: Build the project
        run: npm run build  # Ajusta esto si est치s usando otro build system

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token para el despliegue
